[package]
name = "firebase-types"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/ActuallyHappening/rust-firebase-js/tree/master/firebase-types"
categories = ["api-bindings", "wasm", "web-programming"]
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
license-file = { workspace = true }
# TODO: Add more specific documentation link
documentation = "https://actuallyhappening.github.io/rust-firebase-js/" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "expose-jsvalue"]
serde = ["dep:serde"]
# Requries `serde` feature
expose-jsvalue = ["serde", "dep:wasm-bindgen", "dep:serde-wasm-bindgen"]

[dependencies]
serde = { version = "1.0.160", features = ["derive"], optional = true }
serde-wasm-bindgen = { version = "0.5.0", optional = true }
wasm-bindgen = { version = "0.2.84", optional = true }

[dev-dependencies]
getrandom = { version = "0.2.9", features = ["js"] }
rand = "0.8.5"

