[workspace]
members = [
	"firebase-js",
	"firebase-js-sys",
	"js-bind",
	"js-bind/core",
	"js-bind/proc",
	# "firebase-js-sys/proc",
	# "firebase-js-sys/proc/syner",
	"firebase-types",
]

[workspace.package]
authors = []
homepage = "https://actuallyhappening.github.io/rust-firebase-js/"
repository = "https://github.com/ActuallyHappening/rust-firebase-js"
license = "MIT"
license-file = "LICENSE"
documentation = "https://actuallyhappening.github.io/rust-firebase-js/"
