[package]
name = "js-bind-proc"
description = "Procedural macro exports for js-bind package, see js-bind-core for impls"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/ActuallyHappening/rust-firebase-js/tree/master/firebase-js-sys/proc"
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]
# default = ["strict-feature-checks"]
default = ["strict-feature-checks", "node-not-web"]

strict-feature-checks = []
# default = ["node-not-web"]
# ## For testing purposes
node-not-web = []

[dependencies]
# Local deps
js-bind-core = { path = "../core" }
