# File for tests run concerning js-bind directory

[[bundles]]
if = "testing-slash-examples-feature-flag"
then = "something/path.js"
to-build = "rollup -args"

# [[bundles]]
# if = "link-node"
# then = "something/path.js"
# to-build = "rollup -args"

[doctestgen]
template = """
yippee
"""