[package]
name = "firebase-js-sys"
description = "`wasm32-unknown-unknown` bindings for the Firebase modular JS SDK (`npm` firebase@9)"
version = "0.1.0"
edition = "2021"
authors = []
repository = "https://github.com/ActuallyHappening/rust-firebase-js/tree/master/firebase-js-sys"
license = "MIT"
keywords = ["firebase", "firebase-js", "firebase-database", "wasm", "wasm-bindgen"]
categories = ["wasm", "web-programming"]

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0" }
log = "0.4.17"
wasm-bindgen = { version = "0.2.84" }
