[package]
name = "firebase-js-sys"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0" }
log = "0.4.17"
wasm-bindgen = { version = "0.2.84", features = ["serde"] }
