# File for tests run concerning js-bind directory

[[bundles]]
if = "web-not-node"
then = "js/bundle-esm.js"
to-build = "rollup -args"
web = true

[[bundles]]
if = "node-not-web"
then = "js/bundle-cjs.js"
to-build = "rollup -args"

# [codegen]
# output = "js/bundle.ts"
# template = """
# import { #name as _#name } from '#mod';
# export const #name = _#name;
# """

[doctestgen]
template = """
#[cfg(feature = #web_feature_name)]
wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

use wasm_bindgen::prelude::*;

#[::wasm_bindgen_test::wasm_bindgen_test]
fn #test_name() {
	#code
}
"""