# Config for linking `firebase-js-sys` using `js-bind` crate

[[bundles]]
if = "web-not-node"
then = "js/bundle-esm.js"
to-build = "rollup -args"
web = true

[[bundles]]
if = "node-not-web"
then = "js/bundle-cjs.js"
to-build = "rollup -args"

# [codegen]
# output = "js/bundle.ts"
# template = """
# import { #name as _#name } from '#mod';
# export const #name = _#name;
# """