[package]
name = "js-bind"
version = "0.1.0"
edition = "2021"
description = "wasm32 doctests, multiple wasm32 targets: procedural macros"
authors = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
exclude = [
	"*",
	"!src",
	"!Cargo.toml",
	"!Cargo.lock",
	"!README.md",
]

[features]
## Don't use this, for compiling / testing only
testing-slash-examples-feature-flag = []

[dependencies]

# Local deps
js-bind-proc = { path = "./proc" }
js-bind-core = { path = "./core" }

[dev-dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-test = "0.3.35"

[[example]]
name = "trivial_usage"
required-features = ["testing-slash-examples-feature-flag"]
