[package]
name = "js-bind-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serde = { version = "1.0.160", features = ["derive"] }
js-bind = { path = "../js-bind" }
# toml = "0.7.3"
