[build]
output-dir = "/js"

[build.codegen]
# ts = true # implied
# bundle-name = "bundle" # no ext
# rollup-config = "rollup.config.js"
npm-driver = "pnpm"


[modes.top-level-function]
type = "function"
mod = "example/mod"