[[bundles]]
if = "link-node"
then = "js/bundle-cjs.js"
to-build = "rollup -c js/node.config.mjs"

[[bundles]]
if = "link-web"
then = "js/bundle-esm.js"
to-build = "rollup -c js/web.config.mjs"

[codegen]
output = "js/bundle.ts"
template = """
import { #name as _#name } from '#mod';
export const #name = _#name;
"""